name: Some CI + pushing the benchmark results to another repo

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run stuff
      run: |-
        export FILENAME=benchmark-results-$(date +"%Y-%m-%dT%H-%M-%S").json
        echo "filename=$FILENAME" >> $GITHUB_ENV
        cat sample-benchmark-result.json > $FILENAME
        
    - name: Push changed file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: ${{ env.filename }}
        destination_repo: 'cz4rs/database-repo'
        destination_branch: 'master'
        user_email: 'someone@some-mail.com'
        user_name: 'someone'
